name: "CI" # TODO: split into automatic check and manual data collection workflows

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main

      - name: Run Flake checks
        run: nix flake check --show-trace

      - name: Download previously saved trades
        uses: actions/download-artifact@v4
        with:
          name: trades.csv

      - name: Collect OrderbookV4 trades
        env:
          JSON_RPC_HTTP_URL: ${{ secrets.ARBITRUM_JSON_RPC_HTTP_URL }}
        run: |
          nix develop -c cargo run -- \
            --orderbookv4-deployment-address 0x550878091b2B1506069F61ae59e3A5484Bca9166 \
            --orderbookv4-deployment-block 256576979 \
            --log-level DEBUG

      - name: Archive trades.csv
        uses: actions/upload-artifact@v4
        with:
          name: trades.csv
          path: trades.csv
