name: "CI"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run Flake checks
        run: nix -v flake check --show-trace

      - name: Run Flake checks
        env:
          JSON_RPC_HTTP_URL: ${{ secrets.ARBITRUM_JSON_RPC_HTTP_URL }}
          ORDERBOOKV4_DEPLOYMENT_ADDRESS: 0x550878091b2B1506069F61ae59e3A5484Bca9166
          ORDERBOOKV4_DEPLOYMENT_BLOCK: 256576979
        run: |
          nix -v develop -c cargo run -- --log-level DEBUG

      - name: Archive trades.csv
        uses: actions/upload-artifact@v4
        with:
          name: trades.csv
          path: trades.csv
